org: pedroars99
app: the-gym-app
service: the-gym-app
frameworkVersion: '3'

custom:
  mongoConnStr: ${ssm:/the-gym-app/dev/mongo-connection-string}
  tscpaths:
    - common: common
    - excercises: modules/training/excercises
    - routines: modules/training/routines

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs18.x
  region: eu-central-1
  environment:
    MONGO_CONNECTION_STRING: ${self:custom.mongoConnStr}

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-tscpaths

package:
  patterns:
    - common
    - excercises
    - routines

functions:
  # Routines
  createRoutine:
    handler: modules/training/routines/functions/create-routine.handler
    events:
      - httpApi:
          path: '/routines'
          method: post
  createWorkout:
    handler: modules/training/routines/functions/create-workout.handler
    events:
      - httpApi:
          path: '/routines/{id}/workouts'
          method: post
  deleteWorkout:
    handler: modules/training/routines/functions/delete-workout.handler
    events:
      - httpApi:
          path: '/routines/{routineId}/workouts/{workoutId}'
          method: delete
  getLatestRoutine:
      handler: modules/training/routines/functions/get-latest-routine.handler
      events:
        - httpApi:
            path: '/routines/latest'
            method: get
  getRoutineById:
      handler: modules/training/routines/functions/get-routine-by-id.handler
      events:
        - httpApi:
            path: '/routines/{id}'
            method: get
  getRoutines:
    handler: modules/training/routines/functions/get-routines.handler
    events:
        - httpApi:
            path: '/routines'
            method: get

  # Excercises
  createExcercises:
      handler: modules/training/excercises/functions/create-excercises.handler
      events:
          - httpApi:
              path: '/excercises'
              method: post
  getExcercises:
      handler: modules/training/excercises/functions/get-excercises.handler
      events:
          - httpApi:
              path: '/excercises'
              method: get