service: the-gym-app
frameworkVersion: '3'

custom:
  excercisesTableName: 'excercises-table-${sls:stage}'
  routinesTableName: 'routines-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ ExcercisesTable, Arn ]
            - Fn::GetAtt: [ RoutinesTable, Arn ]
  environment:
    EXCERCISES_TABLE: ${self:custom.excercisesTableName}
    ROUTINES_TABLE: ${self:custom.routinesTableName}

plugins:
  - serverless-plugin-typescript

functions:
  # Routines
  getRoutines:
    handler: modules/training/routines/functions/get-routines.handler
    events:
        - httpApi:
            path: '/routines'
            method: get
  getRoutineById:
      handler: modules/training/routines/functions/get-routine-by-id.handler
      events:
        - httpApi:
            path: '/routines/{id}'
            method: get
  createRoutine:
    handler: modules/training/routines/functions/create-routine.handler
    events:
      - httpApi:
          path: '/routines'
          method: post
  # Excercises
  getExcercises:
      handler: modules/training/excercises/functions/get-excercises.handler
      events:
          - httpApi:
              path: '/excercises'
              method: get

resources:
  Resources:
    ExcercisesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.excercisesTableName}
    RoutinesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.routinesTableName}