name: Deploy Serverless BE

on:
  push:
    branches:
      - main
    paths:
      - serverless/**
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Serverless
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./serverless
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install Dependencies
      run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy
        working-directory: ./serverless
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}